name: publish to nuget
on:
  push:
    branches:
      - release # Default release branch, may also be named 'master' or 'develop'
jobs:
  publish:
    name: build, pack & publish
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET environment
      uses: actions/setup-dotnet@v4
      with:
        # Specify the SDK version you need. Can also use a glob pattern like '8.0.x'
        dotnet-version: '8.0.100' 

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1 # Ensures MSBuild is available

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2 # Ensures NuGet CLI is available

    # - name: Restore dependencies
    #   # The 'dotnet restore' command is the preferred modern way to restore dependencies
    #   run: dotnet restore 

    - name: Restore NuGet packages
      run: nuget restore xControl.Simple.sln # Replace with your solution file

    # - name: Build .NET 4.7 Project
    #   run: msbuild ./xControls.Simple/xControl.Simple.csproj /p:Configuration=Release /p:Platform="Any CPU" /t:Rebuild # Replace with your project name

    - name: Build .NET 4.7 Project
      run: dotnet build  ./xControls.Simple/xControl.Simple.csproj --configuration Release --no-restore
    # - name: Create NuGet Package
    #   working-directory: ./xControls.Simple
    #   run: nuget pack xControl.Simple.csproj -OutputDirectory ../nuget_packages -Properties Configuration=Release # Replace with your project name

    - name: Publish NuGet Package to NuGet.org
      run: nuget push packages/*.nupkg -Source "https://api.nuget.org/v3/index.json" -ApiKey ${{ secrets.NUGET_API_KEY }}
