name: publish to nuget
on:
  push:
    branches:
      - release # Default release branch, may also be named 'master' or 'develop'
jobs:
  publish:
    name: build, pack & publish
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET environment
      uses: actions/setup-dotnet@v4
      with:
        # Specify the SDK version you need. Can also use a glob pattern like '8.0.x'
        dotnet-version: '8.0.100' 

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1 # Ensures MSBuild is available

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2 # Ensures NuGet CLI is available

    - name: Restore dependencies
      # The 'dotnet restore' command is the preferred modern way to restore dependencies
      run: dotnet restore 

    - name: Build .NET 4.7 Project
      run: dotnet build  ./xControls.Simple/xControl.Simple.csproj --configuration Release --no-restore

    - name: Pack the project into a .nupkg file
      run: dotnet pack ./xControls.Simple/xControl.Simple.csproj --configuration Release --no-build --output nupkgs

    - name: Push the NuGet package to nuget.org
      run: dotnet nuget push nupkgs/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source api.nuget.org